apiVersion: v1
kind: Service
metadata:
  name: swiggy-service
  labels:
    app: swiggy
spec:
  selector:
    app: swiggy
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
